# Public certificate for root domain or wildcard.
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CT:
    Type: String
    Description: Whether this project is top secret yet now (select DISABLED) or for publish right now (select ENABLED)
    AllowedValues:
      - DISABLED
      - ENABLED
  DomainName:
    Type: String
    Description: Domain name
    AllowedPattern: '[a-z0-9\.]+'
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Hosted Zone ID for validation
  OrganizationName:
    Type: String
    Description: for this domain to use for Name (lowercasewithoutspace)
    AllowedPattern: "[a-z0-9]+"
  ProjectName:
    Type: String
    Description: Project(Service) name (lowercasewithoutspace)
    AllowedPattern: '[a-z0-9]*'
  Purpose:
    Type: String
    Description: Whether this certificate is root-domain or wildcard
    AllowedValues:
      - root-domain
      - wildcard
    Default: wildcard
Conditions:
  ProjectNameIsEmpty: !Equals [!Ref ProjectName, ""]
  PurposeIsWildcard: !Equals [!Ref Purpose, "wildcard"]
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: !Ref CT
      DomainName: !If
        - PurposeIsWildcard
        - !Sub "*.${DomainName}"
        - !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          # To automate to register CNAME.
          # see: https://dev.classmethod.jp/articles/acm-extends-automation-certificate-issuance-via-cloudformation/
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub "${OrganizationName}:certificatemanager-certificate-${Purpose}"
        - Fn::If:
            - ProjectNameIsEmpty
            - !Ref AWS::NoValue
            - Key: Project
              Value: !Ref ProjectName
      ValidationMethod: DNS
Outputs:
  Certificate:
    Value: !Ref Certificate
    Export:
      Name: !Sub "${AWS::StackName}-Certificate"
