# S3 hosting.
# CloudFront distribution is standard equipment.
# @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-s3.html
# @see https://qiita.com/okubot55/items/8290b6c1f59efcff1cb9
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Type: String
    Description: Bucket name in case when staging
    AllowedPattern: '[a-z0-9\.]+'
  Environment:
    Type: String
    Description: Environment ("prd" or "stg")
    AllowedValues:
      - prd
      - stg
  ProjectName:
    Type: String
    Description: Project(Service) name (lowercasewithoutspace)
    AllowedPattern: '[a-z0-9]+'
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      # see: https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html
      # > These bucket names must exactly match your domain name.
      BucketName: !Ref BucketName
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}:${Environment}-s3-bucket-hosting"
        - Key: Project
          Value: !Ref ProjectName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action: ["s3:GetObject"]
            Effect: Allow
            Principal: "*"
            Resource: !Sub "arn:aws:s3:::${Bucket}/*"
Outputs:
  BucketName:
    Value: !Ref Bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  WebsiteURL:
    Value: !GetAtt Bucket.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"
