# S3 hosting.
# CloudFront distribution is standard equipment.
# @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-s3.html
# @see https://qiita.com/okubot55/items/8290b6c1f59efcff1cb9
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Type: String
    Description: Bucket name in case when staging
    AllowedPattern: '[a-z0-9\.]+'
  IpToAllowAccess:
    Type: String
    Description: Public IP address to allow access to bucket
    AllowedPattern: '(((\d{1,3})\.){3}\d{1,3}/\d{1,2})?'
  ProjectName:
    Type: String
    Description: Project(Service) name (lowercasewithoutspace)
    AllowedPattern: '[a-z0-9]+'
  TemplateBucketHost:
    Type: String
    Description: Bucket host which put CloudFormation template (excludeing "https://")
    AllowedPattern: '[a-z0-9\-\.]+'
Resources:
  BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketHost}/s3_hosting_bucket.yml"
      Parameters:
        BucketName: !Ref BucketName
        Environment: stg
        IpToAllowAccess: !Ref IpToAllowAccess
        ProjectName: !Ref ProjectName
      TimeoutInMinutes: 1
Outputs:
  BucketName:
    Value: !GetAtt BucketStack.Outputs.BucketName
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  WebsiteURL:
    Value: !GetAtt BucketStack.Outputs.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"
